### ISSUE TITLE
Create the CONTRBUTING.md 

### ISSUE THREAD

**Issue by OSCA-Ado-Ekiti** [OSCA-Ado-Ekiti/Hacktoberfest2022-Ekiti#16]
Hello there, please there is a need for the contributing guide on this repo, here is a sample you can see to make yours, also see ways to improve the guide to make it easier for the consumption of everyone: https://github.com/OSCA-Ado-Ekiti/Hacktoberfest2021-Ekiti/blob/main/CONTRIBUTING.md

**Comment by praistarr** [comment]
I will pick this up

**Comment by OgunmisiM** [comment]
Is anyone assigned to this yet?
