### ISSUE TITLE
Content: create the about page texts

### ISSUE THREAD

**Issue by OSCA-Ado-Ekiti** [OSCA-Ado-Ekiti/Hacktoberfest2022-Ekiti#50]
Hello there, there is a need for "about" of the Hacktoberfest Ekiti Good first Issues Website, example of the content needed can be shadowed here: https://goodfirstissues.com/about.html

**Comment by Victorayo** [comment]
Assign me this pls

**Comment by saintmalik** [comment]
👀👀

**Comment by Victorayo** [comment]
> Hello there, there is a need for "about" of the Hacktoberfest Ekiti Good first Issues Website, example of the content needed can be shadowed here: https://goodfirstissues.com/about.html

I've made a pull request on it already. Good morning from here sir 🙇‍♂️

**Comment by OSCA-Ado-Ekiti** [comment]
merged, thanks for contributing
