### ISSUE TITLE
creating the header section

### ISSUE THREAD

**Issue by OSCA-Ado-Ekiti** [OSCA-Ado-Ekiti/Hacktoberfest2022-Ekiti#56]
hello there, using the javascript framework(ReactJS), kindly work on the Header section of the following design:

https://www.figma.com/file/DpprZJcFmrOzaQRJbZepkr/hactoberfest?node-id=0%3A1

**Comment by devchaos0** [comment]
Can you assign me to this

**Comment by Victorayo** [comment]
> Can you assign me to this

@OSCA-Ado-Ekiti

**Comment by Manishgupta200** [comment]
I can solve this issue just in one day because this things happens to my project also. So, i'm familiar of this kind. Assign it to me

**Comment by OSCA-Ado-Ekiti** [comment]
hii @Manishgupta200 can you pick other issues? this has been solved

**Comment by Manishgupta200** [comment]
Ya sure
