### ISSUE TITLE
Workflow: Write the linting workflow

### ISSUE THREAD

**Issue by OSCA-Ado-Ekiti** [OSCA-Ado-Ekiti/Hacktoberfest2022-Ekiti#58]
Hello there, here is an issue to write the github workflo that checks the code to see if it follows the layed down rules, hence on every pull request it runs the linting check

**Comment by Elijah699** [comment]
Can I work on this @saintmalik

**Comment by saintmalik** [comment]
sure, but looks like someone is, it will be assigned

**Comment by Elijah699** [comment]
@saintmalik @OSCA-Ado-Ekiti Please review my PR

**Comment by OSCA-Ado-Ekiti** [comment]
fixed #85
