### ISSUE TITLE
Create Logo

### ISSUE THREAD

**Issue by Victorayo** [OSCA-Ado-Ekiti/Hacktoberfest2022-Ekiti#59]
Cc: @OSCA-Ado-Ekiti 
We need a simple and more techie logo for Hacktoberfest Ekiti web app.

This is the link to the previous one done last year. Check here 
https://github.com/OSCA-Ado-Ekiti/Hacktoberfest2021-Ekiti/issues/50

Pls make sure these are included in your submission;
- The idea behind your logo.
- Your sketch
- Black and white version of the logo
- 1-3 Mock-ups to show how it will look.
- file formats such as SVG, JPEG, PNG (for now)

**Comment by motolanicephas** [comment]
Assigne

**Comment by Victorayo** [comment]
> Assigne

@saintmalik @OSCA-Ado-Ekiti

**Comment by sowmiyeh** [comment]
Hi @Victorayo, Could you please assign me this issue? I'll try to complete ASAP

**Comment by saintmalik** [comment]
assigned @sowmiya-venkatesan

**Comment by Victorayo** [comment]
> Hi @Victorayo, Could you please assign me this issue? I'll try to complete ASAP

Thanks for taking up the issue 🤝
