### ISSUE TITLE
Create a light mood of the header section

### ISSUE THREAD

**Issue by Victorayo** [OSCA-Ado-Ekiti/Hacktoberfest2022-Ekiti#60]
Cc: @OSCA-Ado-Ekiti 
hello there, using the javascript framework(ReactJS), kindly work on the Header section of the following design:

Create a light mood of the header section

Issue #61

**Comment by devchaos0** [comment]
assignment this please

**Comment by Victorayo** [comment]
> assignment this please

@OSCA-Ado-Ekiti @saintmalik
