### ISSUE TITLE
Design Mockups

### ISSUE THREAD

**Issue by Victorayo** [OSCA-Ado-Ekiti/Hacktoberfest2022-Ekiti#62]
Cc: @OSCA-Ado-Ekiti 
Hi there, kindly design 1-3 attractive Mockups of the Good first issue webpage we're working on issue #17 

The link to the Figma file: 
https://www.figma.com/file/DpprZJcFmrOzaQRJbZepkr/hactoberfest?node-id=0%3A1

Check below samples for inspiration.

![images (5)](https://user-images.githubusercontent.com/53627044/196309033-4d3737e2-1f66-48c4-9608-8ae4a0bdc8b0.jpeg)
![images](https://user-images.githubusercontent.com/53627044/196309036-33242213-857e-4dcb-a047-7b5378bca3eb.jpeg)

**Comment by oritselaye** [comment]
Can I be assigned this task? @saintmalik

**Comment by OSCA-Ado-Ekiti** [comment]
it has been assigned to you

**Comment by Victorayo** [comment]
Any progress with this?

**Comment by sowmiyeh** [comment]
Hi @OSCA-Ado-Ekiti , Could you please brief this issue a bit more, so that I can take it up ?

**Comment by OSCA-Ado-Ekiti** [comment]
its not needed anymore @sowmiya-venkatesan , this issue has been closed
