### ISSUE TITLE
Cleanup: Move the codes to a folder

### ISSUE THREAD

**Issue by OSCA-Ado-Ekiti** [OSCA-Ado-Ekiti/Hacktoberfest2022-Ekiti#64]
Hello there, to avoiid things looking messy and to make everything professional enough, can someone pick this issue and move the codebase files(*.js) to a folder called web.

**Comment by Fadahunsiseyi** [comment]
I will pick this up

**Comment by OSCA-Ado-Ekiti** [comment]
fixed  #65
