### ISSUE TITLE
Create the issue filtering section

### ISSUE THREAD

**Issue by OSCA-Ado-Ekiti** [OSCA-Ado-Ekiti/Hacktoberfest2022-Ekiti#79]
hello there, using the javascript framework(ReactJS), kindly work on the issue filtering section of the following design:

https://www.figma.com/file/DpprZJcFmrOzaQRJbZepkr/hactoberfest?node-id=0%3A1

**Comment by Tuasegun** [comment]
assign this to me thanks

**Comment by OSCA-Ado-Ekiti** [comment]
assigned

**Comment by Tuasegun** [comment]
done, does this include functionality??

**Comment by OSCA-Ado-Ekiti** [comment]
solved #90
