### ISSUE TITLE
Create the main section of the design

### ISSUE THREAD

**Issue by OSCA-Ado-Ekiti** [OSCA-Ado-Ekiti/Hacktoberfest2022-Ekiti#82]
hello there, using the javascript framework(ReactJS), kindly work on the issue main section of the following design, where we have the boxes that carries the issues title

https://www.figma.com/file/DpprZJcFmrOzaQRJbZepkr/hactoberfest?node-id=0%3A1

**Comment by Elijah699** [comment]
@OSCA-Ado-Ekiti I will like to work on this

**Comment by OSCA-Ado-Ekiti** [comment]
solved #94
