### ISSUE TITLE
Create the about page of the design

### ISSUE THREAD

**Issue by OSCA-Ado-Ekiti** [OSCA-Ado-Ekiti/Hacktoberfest2022-Ekiti#83]
hello there, using the javascript, html, kindly work on the issue about page section of the following design, where we have the boxes that carries the issues title

https://www.figma.com/file/DpprZJcFmrOzaQRJbZepkr/hactoberfest?node-id=0%3A1

**Comment by Anurag-Singh-04** [comment]
Hey @OSCA-Ado-Ekiti can you please explain me what changes you want in the website.

**Comment by OSCA-Ado-Ekiti** [comment]
if you check the design from the links added, you will see there is an about page, thats the page to be created

**Comment by MunavvarSinan** [comment]
can u assign me to this task if it's not done yet

**Comment by Anurag-Singh-04** [comment]
Hey @OSCA-Ado-Ekiti can you please assign me this issue.

**Comment by OSCA-Ado-Ekiti** [comment]
yes

**Comment by Tuasegun** [comment]
@OSCA-Ado-Ekiti  assign this to me please

**Comment by OSCA-Ado-Ekiti** [comment]
@Anurag-Singh-04 hello there, are you still working on this?

**Comment by Anurag-Singh-04** [comment]
I wont be able to complete this issue @OSCA-Ado-Ekiti you can assign it to someone else

**Comment by OSCA-Ado-Ekiti** [comment]
okay

**Comment by OSCA-Ado-Ekiti** [comment]
solved #97 #98
